### Dodawanie pięciu studentów
POST http://localhost:8080/students/add/Halford/Smith
###
POST http://localhost:8080/students/add/Thomas/Tarantino
###
POST http://localhost:8080/students/add/Elvis/Ratzinger
###
POST http://localhost:8080/students/add/Emma/Talyor
###
POST http://localhost:8080/students/add/Jessica/Swift

### Usuwanie studenta o ID = 5
DELETE http://localhost:8080/students/delete/5

### Dodawanie czterech kursów
GET http://localhost:8080/add_course/PSI
###
GET http://localhost:8080/add_course/ZPO
###
GET http://localhost:8080/add_course/RIOBD
###
GET http://localhost:8080/add_course/AD

### Usuwanie kursu o ID = 4
GET http://localhost:8080/add_course/AD



###
GET http://localhost:8080/add_grade/1/2/10
###
GET http://localhost:8080/grades/1
###
GET http://localhost:8080/remove_course/1
###

